### ISSUE TITLE
[Backend] Follow & Block API documentation discussion

### ISSUE THREAD

**Issue by supiket** [bounswe/2021SpringGroup2#322]
Help needed on [follow & block API documentation](https://github.com/bounswe/2021SpringGroup2/wiki/Follow-&-Block-API-Documentation).

Follow & block functionalities are implemented based on current documentation (See [#308](https://github.com/bounswe/2021SpringGroup2/issues/308)) in `follow` branch.

**Comment by ege-kaya** [comment]
I have a few comments: for the block/unblock and follow/unfollow methods, first off I think the path parameter (not the body parameter) should be the name of the blocked/unblocked or followed/unfollowed user. So for example when we post to /api/users/<some_user>/block/, we should block the user with the username _some\_user_. The same should go with the unblock and follow/unfollow methods. Also, we don't need to provide the name of the user performing the action (the user who is following/unfollowing somebody etc.) because we can get his username automatically from the JWT authorization token sent with the request. 

These are my comments, I think the responses and everything look good and comply with Activity Streams, when these are changed we should be fine.

**Comment by supiket** [comment]
Thanks for your comments, Ege.

The implementation is actually similar to what you described, I have now modified the documentation to match these.
I will be updating the code as well, in order not to provide the name of the user performing the action.

Will close this issue if there are no further comments on the updated version of the documentation. 
The details of implementation are linked to the related issue [#308](https://github.com/bounswe/2021SpringGroup2/issues/308)
